### ISSUE TITLE
Support kedro 0.19.x

### ISSUE THREAD

**Issue by takikadiri** [takikadiri/kedro-boot#9]
`kedro-boot` is slightly impacted by these kedro 0.19.x breaking changes :

- Changes in datasets arguments, attributes and method naming (ex: from data_sets to datasets)
- Remove of `create_default_data_set()` method in the `Runner` in favour of using dataset factories to create default dataset instances. 

Since the next ``kedro-boot`` release will break a lot of user facing interfaces (AppPipeline, template params, some refactoring), i think that we need to make effort to support kedro 0.18.x alongside 0.19.x. I'm not aware how rapidly users migrate to 0.19.x

**Comment by Galileo-Galilei** [comment]
[People have clearly not migrated yet ](https://www.pepy.tech/projects/kedro?versions=0.19.0&versions=0.19.1&versions=0.18.14&versions=0.18.*) .

That said since there is a MVP compatible with 0.18, I feel it is acceptable to break things since it is not mature yet, but it's up to you!

**Comment by konstantinkobs** [comment]
In my opinion, I also think that only supporting the newest version of Kedro is okay. Since many things will change over time for Kedro, it is not desirable to have such technical debt in this project as well.

**Comment by takikadiri** [comment]
It makes sens. We're going to support only kedro > 0.19.x
